"""Fixed-version, non-executing BPL compilation and explicit coverage limits."""
from __future__ import annotations

import json
import math
from pathlib import Path
import re
import signal
import subprocess
import tempfile

COMPILER_COMMIT = "4e505740f5025d59ba655c6c955f83876f753007"
COMPILER_VERSION = "2.4.0"
COMPILER_TREE = "7dd2a3fbd9199e57687a8a4f71df2aaecc724ba12aafe20cd7fd4566b74073c9"
RULE_VERSION = "bridge-bpl-scope-2"
BPL_LIMIT = 128 * 1024
OUTPUT_LIMIT = 8 * 1024 * 1024
TIMEOUT = 30

# This fixed trusted bootstrap is not generated by the model. Limits are set in
# the child itself: preexec_fn would be unsafe in the threaded Web service.
_CHILD = r"""
import contextlib, hashlib, importlib.util, importlib.metadata, io, json, resource, sys
from pathlib import Path
resource.setrlimit(resource.RLIMIT_AS, (512 * 1024**2,) * 2)
resource.setrlimit(resource.RLIMIT_CPU, (30, 30))
resource.setrlimit(resource.RLIMIT_FSIZE, (8 * 1024**2,) * 2)
resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
limit = 8 * 1024**2
result = {"stages": [], "ast": None, "plan": None, "verified": False}
try:
    spec = importlib.util.find_spec("bpl")
    if not spec or not spec.origin or sys.version_info < (3, 13):
        raise ValueError("runtime")
    base = Path(spec.origin).parent
    digest = hashlib.sha256()
    for path in sorted(base.rglob("*")):
        if path.is_file() and "__pycache__" not in path.parts and path.suffix not in (".pyc", ".pyo"):
            digest.update(path.relative_to(base).as_posix().encode() + b"\0" + path.read_bytes() + b"\0")
    if digest.hexdigest() != sys.argv[1] or importlib.metadata.version("bpl") != sys.argv[2]:
        raise ValueError("pin")
    result["verified"] = True
    from bpl.cli.main import main
    for stage in ("parse", "validate", "lower"):
        args = [stage, "input.bpl", "--json-errors"]
        if stage == "parse":
            args += ["--with-spans", "--out", "ast.json"]
        else:
            args += ["--target", "human"]
            if stage == "lower":
                args += ["--out", "plan.json"]
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = main(args)
        if len(out.getvalue().encode()) + len(err.getvalue().encode()) > limit:
            raise ValueError("output")
        if sum(p.stat().st_size for p in Path(".").rglob("*") if p.is_file()) > limit:
            raise ValueError("output")
        diagnostics = []
        raw = err.getvalue().strip()
        if raw:
            try:
                payload = json.loads(raw)
                diagnostics = payload.get("diagnostics", []) if isinstance(payload, dict) else payload
            except ValueError:
                diagnostics = [{"code": "compiler_diagnostic_unavailable", "message": "See stage exit status."}]
        result["stages"].append({"stage": stage, "exit_code": code, "diagnostics": diagnostics})
        if stage == "parse" and code == 0:
            result["ast"] = json.loads(Path("ast.json").read_text())
        if stage == "lower" and code == 0:
            result["plan"] = json.loads(Path("plan.json").read_text())
        if code:
            break
except BaseException:
    result["unavailable"] = True
encoded = json.dumps(result, ensure_ascii=False).encode()
if len(encoded) > limit:
    encoded = b'{"unavailable":true,"verified":false,"stages":[]}'
sys.stdout.buffer.write(encoded)
"""


def child_environment():
    return {"PATH": "/usr/bin:/bin", "LANG": "C.UTF-8", "LC_ALL": "C.UTF-8",
            "OPENBLAS_NUM_THREADS": "1", "OMP_NUM_THREADS": "1", "MKL_NUM_THREADS": "1",
            "PYTHONDONTWRITEBYTECODE": "1"}


def _issue(code, message, line=None, column=None):
    issue = {"code": code, "message": message, "line": line}
    if column is not None:
        issue["column"] = column
    return issue


def _input_problem(text):
    if not isinstance(text, str) or not text.strip() or "\0" in text:
        return _issue("invalid_bpl_text", "BPL 草稿为空或包含不支持的字符。")
    if len(text.encode("utf-8")) > BPL_LIMIT:
        return _issue("bpl_size_limit", "BPL 草稿超过 128 KiB，未进行检查。")
    # Remove literal/comment contents before recognizing module keywords.
    code = re.sub(r'"(?:\\.|[^"\\])*"|//[^\n]*|/\*.*?\*/', " ", text, flags=re.S)
    if re.search(r"\b(?:import|module)\b", code):
        return _issue("external_module_forbidden", "本次检查不接受外部模块或 import。")
    literals = re.findall(r'"(?:\\.|[^"\\])*"', text)
    for literal in literals:
        try:
            part = json.loads(literal)
        except ValueError:
            part = literal.strip('"')
        if re.search(r'(?:^|\s)(?:/|~[/\\]|[A-Za-z]:[/\\]|\\\\|\.[/\\])|\.\.[/\\]|(?:file|https?)://', part):
            return _issue("external_path_forbidden", "本次检查不接受附件指定的文件路径或外部地址。")
    return None


def walk_nodes(value):
    if isinstance(value, dict):
        if "node_type" in value:
            yield value
        for item in value.values():
            yield from walk_nodes(item)
    elif isinstance(value, list):
        for item in value:
            yield from walk_nodes(item)


def _span(node):
    span = node.get("span") or {}
    return (span.get("start_line"), span.get("end_line"))


def scope_limits(ast, plan):
    """Account for upstream's measured gaps; never repair experimental values."""
    issues = []
    nodes = list(walk_nodes(ast))
    plans = (plan or {}).get("steps", [])
    protocols = [node for node in nodes if node.get("node_type") == "ProtocolDecl"]
    if len(protocols) != 1:
        issues.append(_issue("multiple_protocols", "编译路径只处理第一个 protocol，其余内容未完整检查。"))
    for node in nodes:
        kind = node.get("node_type", "")
        line, end_line = _span(node)
        if kind.endswith("Decl") and kind != "ProtocolDecl":
            issues.append(_issue("declaration_semantics_unchecked", "材料、容器或其他声明的实验语义未核实。", line))
        if kind.endswith("Stmt") and kind != "CallStmt":
            issues.append(_issue("statement_not_lowered", "此语句的执行含义未获当前编译路径完整处理。", line))
        if kind != "CallStmt":
            continue
        matched = [step for step in plans if (
            step.get("annotations", {}).get("source_span", {}).get("start_line"),
            step.get("annotations", {}).get("source_span", {}).get("end_line")) == (line, end_line)]
        if not matched:
            issues.append(_issue("statement_not_lowered", "此源步骤未在编译计划中找到对应项。", line))
        name = node.get("name", "").lower()
        args = {arg.get("name"): arg.get("value") or {} for arg in node.get("arguments", [])}
        if name == "transfer":
            issues.append(_issue("container_mapping_unverified", "编译器可能生成容器/孔位映射；这不是实际实验容器记录。", line))
            volume = args.get("volume", {})
            unit = (volume.get("unit") or {}).get("text") if volume.get("node_type") == "QuantityExpr" else None
            raw = (volume.get("value") or {}).get("value") if isinstance(volume.get("value"), dict) else None
            if unit not in {"uL", "mL", "L", "nL"} or not isinstance(raw, (int, float)):
                issues.append(_issue("volume_dimension_unchecked", "此体积量纲/数值未获可信的单位检查。", line))
            else:
                expected = raw * {"uL": 1, "mL": 1000, "L": 1000000, "nL": .001}[unit]
                observed = [step["primitive"].get("volume_ul") for step in matched
                            if "volume_ul" in step.get("primitive", {})]
                if any(not isinstance(value, (int, float)) or not math.isclose(value, expected) for value in observed):
                    issues.append(_issue("volume_mapping_changed", "编译产物的体积换算与原 BPL 不一致；不可用作实验参数。", line))
        elif name == "wait":
            duration = args.get("duration", {})
            number = duration.get("value") if duration.get("node_type") == "QuantityExpr" else None
            raw = number.get("value") if isinstance(number, dict) and number.get("node_type") == "NumberLit" else None
            unit = (duration.get("unit") or {}).get("text")
            units = {"s": 1, "sec": 1, "second": 1, "seconds": 1, "min": 60, "minute": 60,
                     "minutes": 60, "h": 3600, "hr": 3600, "hour": 3600, "hours": 3600}
            if not isinstance(raw, (int, float)) or raw <= 0:
                issues.append(_issue("duration_unresolved", "编译器未能解析等待时长；这不等于原文缺失，默认时长不能替代原文或用户回答。",
                                     line, (node.get("span") or {}).get("start_col")))
            elif unit not in units:
                issues.append(_issue("duration_dimension_unchecked", "等待时长的单位未经核实。", line))
            elif any(step.get("primitive", {}).get("duration_s") != raw * units[unit] for step in matched):
                issues.append(_issue("duration_mapping_changed", "编译时长与原 BPL 不一致；保留原文待核对。", line))
        else:
            issues.append(_issue("human_step_unchecked", "该操作仅作为人工步骤保留，参数和生物学含义未被验证。", line))
    # Preserve order but collapse duplicate annotations for one source position.
    return list({(item["code"], item["line"], item.get("column")): item for item in issues}.values())


def compile_bpl(text: str, python: str | None) -> dict:
    value = {"syntax_state": "not_run", "compiler_state": "not_run", "diagnostics": [],
             "unchecked": [], "ast": None, "plan": None, "stages": [],
             "compiler": {"commit": COMPILER_COMMIT, "version": COMPILER_VERSION,
                          "tree_sha256": COMPILER_TREE, "rule_version": RULE_VERSION, "verified": False}}
    problem = _input_problem(text)
    if problem:
        value["diagnostics"].append(problem)
        return value
    if not python:
        value["compiler_state"] = "unavailable"
        value["diagnostics"].append(_issue("compiler_not_configured", "固定版本编译器尚不可用；草稿可保留待核对。"))
        return value
    try:
        with tempfile.TemporaryDirectory(prefix="bridge-bpl-") as directory:
            root = Path(directory)
            (root / "input.bpl").write_text(text)
            with (root / "result.json").open("wb") as out, (root / "stderr.txt").open("wb") as err:
                process = subprocess.Popen([python, "-I", "-c", _CHILD, COMPILER_TREE, COMPILER_VERSION],
                                           cwd=root, env=child_environment(), stdout=out, stderr=err,
                                           start_new_session=True)
                try:
                    process.wait(timeout=TIMEOUT)
                except subprocess.TimeoutExpired:
                    # The group belongs to this exact newly spawned child only.
                    try:
                        import os
                        os.killpg(process.pid, signal.SIGKILL)
                    except ProcessLookupError:
                        pass
                    process.wait()
                    raise ValueError("compiler_resource_limit") from None
            if process.returncode or sum(p.stat().st_size for p in root.rglob("*") if p.is_file()) > OUTPUT_LIMIT:
                raise ValueError("compiler_resource_limit")
            result = json.loads((root / "result.json").read_bytes())
        value["compiler"]["verified"] = result.get("verified") is True
        value["ast"], value["plan"] = result.get("ast"), result.get("plan")
        for stage in result.get("stages", []):
            value["stages"].append({"stage": stage["stage"], "exit_code": stage["exit_code"]})
            for item in stage.get("diagnostics", []):
                if isinstance(item, dict):
                    location = item.get("location") or {}
                    value["diagnostics"].append(_issue(
                        str(item.get("code", "compiler_diagnostic"))[:120],
                        str(item.get("message", ""))[:1600], location.get("start", {}).get("line")))
            if stage["stage"] == "parse":
                value["syntax_state"] = "passed" if stage["exit_code"] == 0 else "failed"
            else:
                value["compiler_state"] = "passed" if stage["exit_code"] == 0 else "failed"
        if result.get("unavailable") or not result.get("verified"):
            raise ValueError("compiler_unavailable")
        if value["ast"]:
            value["unchecked"] = scope_limits(value["ast"], value["plan"])
    except (OSError, ValueError, KeyError, TypeError, RecursionError):
        value["compiler_state"] = "unavailable"
        value["diagnostics"].append(_issue("compiler_unavailable", "编译器不可用或超出资源限制；不表示方案错误。"))
    return value
